import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      screens: {
        tv: "1920px",
      },
      colors: {
        surface: "#16130e",
        "surface-dim": "#16130e",
        "surface-bright": "#3d3933",
        "surface-container-lowest": "#110e09",
        "surface-container-low": "#1e1b16",
        "surface-container": "#231f1a",
        "surface-container-high": "#2d2924",
        "surface-container-highest": "#38342e",
        "on-surface": "#e9e1d8",
        "on-surface-variant": "#d1c5b4",
        "inverse-surface": "#e9e1d8",
        "inverse-on-surface": "#34302a",
        outline: "#9a8f80",
        "outline-variant": "#4e4639",
        "surface-tint": "#e9c176",
        primary: "#e9c176",
        "on-primary": "#412d00",
        "primary-container": "#c5a059",
        "on-primary-container": "#4e3700",
        "inverse-primary": "#775a19",
        "primary-fixed": "#ffdea5",
        "primary-fixed-dim": "#e9c176",
        "on-primary-fixed": "#261900",
        "on-primary-fixed-variant": "#5d4201",
        secondary: "#bfc5e4",
        "on-secondary": "#292f48",
        "secondary-container": "#424862",
        "on-secondary-container": "#b1b7d6",
        "secondary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#bfc5e4",
        "on-secondary-fixed": "#141a32",
        "on-secondary-fixed-variant": "#3f465f",
        tertiary: "#b0c6f9",
        "on-tertiary": "#173059",
        "tertiary-container": "#8fa5d6",
        "on-tertiary-container": "#233a65",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#b0c6f9",
        "on-tertiary-fixed": "#001a41",
        "on-tertiary-fixed-variant": "#304671",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#16130e",
        "on-background": "#e9e1d8",
        "surface-variant": "#38342e",
        "background-deep": "#060A1A",
        "surface-panel": "#111A35",
        "accent-bronze": "#A37E3E",
        "text-muted": "#8E9BB1",
        "text-on-dark": "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "margin-page": "48px",
        "gutter-grid": "24px",
        "panel-padding": "32px",
        "stage-gap": "64px",
      },
      fontFamily: {
        "clock-display": ["Playfair Display", "serif"],
        "clock-display-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "tabular-nums": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "clock-display": [
          "200px",
          { lineHeight: "200px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "clock-display-mobile": [
          "100px",
          { lineHeight: "100px", fontWeight: "700" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-md": ["18px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.15em", fontWeight: "700" },
        ],
        "tabular-nums": ["20px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
